=== AlfieJ/KarmaTestAdapter/KarmaTestAdapter.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "JSON schema for KarmaTestAdapter configuration files (KarmaTestAdapter.json)",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "KarmaConfigFile": {
            "description": "Use this if you want to use a karma configuration file not named karma.conf.js.",
            "type": "string"
        },
        "Disabled": {
            "description": "Set to true, if the Karma test adapter should be disabled for this karma configuration file.",
            "type": "boolean"
        },
        "LogToFile": {
            "description": "Set to true, if you want the adapter to write log statements to a log file (named KarmaTestAdapter.log).",
            "type": "boolean"
        },
        "LogDirectory": {
            "description": "Where the log file should be saved (if LogToFile is true). If this property is not specified the directory in which KarmaTestAdapter.json resides is used.",
            "type": "string"
        },
        "config": {
            "description": "This property overwrites any configurations from the karma configuration file.",
            "type": "object",
            "additionalProperties": true
        }
    }
}

=== AlfieJ/KarmaTestAdapter/TestProjects/KarmaRequireJasmine/ui/KarmaTestAdapter.json
{
    "$schema": "http://MortenHoustonLudvigsen.github.io/KarmaTestAdapter/KarmaTestAdapter.schema.json",
    "KarmaConfigFile": "karma.conf.src.js",
    "Disabled": false,
    "LogToFile": true,
    "LogDirectory": "TestResults/Karma",
    "config": {
        "browsers": [
            "Chrome" 
        ]
    }
}
